// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: ingest.proto

package ingestservice

import (
	"context"

	ingestv1 "github.com/Lio6x1/meshops/gen/ingest/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	EventError                 = ingestv1.EventError
	ReportEntityStatesRequest  = ingestv1.ReportEntityStatesRequest
	ReportEntityStatesResponse = ingestv1.ReportEntityStatesResponse

	IngestService interface {
		ReportEntityStates(ctx context.Context, opts ...grpc.CallOption) (ingestv1.IngestService_ReportEntityStatesClient, error)
	}

	defaultIngestService struct {
		cli zrpc.Client
	}
)

func NewIngestService(cli zrpc.Client) IngestService {
	return &defaultIngestService{
		cli: cli,
	}
}

func (m *defaultIngestService) ReportEntityStates(ctx context.Context, opts ...grpc.CallOption) (ingestv1.IngestService_ReportEntityStatesClient, error) {
	client := ingestv1.NewIngestServiceClient(m.cli.Conn())
	return client.ReportEntityStates(ctx, opts...)
}
