CREATE DATABASE IF NOT EXISTS meshops_review_history_20260912;
USE meshops_review_history_20260912;
CREATE TABLE entity_history_samples LIKE meshops_course.entity_history_samples;
INSERT INTO entity_history_samples (tenant_id,entity_id,occurred_at,sampled_at,event_id,source_id,entity_version,snapshot,sample_reason)
SELECT 'review','drone-001','2026-09-10','2026-09-10',CONCAT('event-',a.n+10*b.n+100*c.n+1000*d.n+10000*e.n),'source',1,JSON_OBJECT(),'periodic'
FROM (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a
CROSS JOIN (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b
CROSS JOIN (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c
CROSS JOIN (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
CROSS JOIN (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) e;
ANALYZE TABLE entity_history_samples;
SELECT 'case-A-no-expired' AS experiment;
EXPLAIN ANALYZE SELECT id FROM entity_history_samples WHERE sampled_at<'2026-09-05' OR occurred_at<'2026-09-05' ORDER BY id LIMIT 500;
EXPLAIN ANALYZE SELECT id FROM entity_history_samples WHERE sampled_at<'2026-09-05' ORDER BY sampled_at,id LIMIT 500;
EXPLAIN ANALYZE SELECT id FROM entity_history_samples WHERE occurred_at<'2026-09-05' ORDER BY occurred_at,id LIMIT 500;
UPDATE entity_history_samples SET occurred_at='2026-09-04' WHERE id>99990;
ANALYZE TABLE entity_history_samples;
SELECT 'case-B-sparse-expired' AS experiment;
EXPLAIN ANALYZE SELECT id FROM entity_history_samples WHERE sampled_at<'2026-09-05' OR occurred_at<'2026-09-05' ORDER BY id LIMIT 500;
EXPLAIN ANALYZE SELECT id FROM entity_history_samples WHERE occurred_at<'2026-09-05' ORDER BY occurred_at,id LIMIT 500;
EXPLAIN FORMAT=JSON SELECT id FROM entity_history_samples WHERE sampled_at<'2026-09-05' OR occurred_at<'2026-09-05' ORDER BY id LIMIT 500 FOR UPDATE;