// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: task.proto

package taskservice

import (
	"context"

	taskv1 "github.com/Lio6x1/meshops/gen/task/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CancelTaskRequest      = taskv1.CancelTaskRequest
	CancelTaskResponse     = taskv1.CancelTaskResponse
	CreateTaskRequest      = taskv1.CreateTaskRequest
	CreateTaskResponse     = taskv1.CreateTaskResponse
	GetTaskHistoryRequest  = taskv1.GetTaskHistoryRequest
	GetTaskHistoryResponse = taskv1.GetTaskHistoryResponse
	GetTaskRequest         = taskv1.GetTaskRequest
	GetTaskResponse        = taskv1.GetTaskResponse
	ListTasksRequest       = taskv1.ListTasksRequest
	ListTasksResponse      = taskv1.ListTasksResponse

	TaskService interface {
		CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error)
		CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error)
		GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error)
		ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
		GetTaskHistory(ctx context.Context, in *GetTaskHistoryRequest, opts ...grpc.CallOption) (*GetTaskHistoryResponse, error)
	}

	defaultTaskService struct {
		cli zrpc.Client
	}
)

func NewTaskService(cli zrpc.Client) TaskService {
	return &defaultTaskService{
		cli: cli,
	}
}

func (m *defaultTaskService) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error) {
	client := taskv1.NewTaskServiceClient(m.cli.Conn())
	return client.CreateTask(ctx, in, opts...)
}

func (m *defaultTaskService) CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error) {
	client := taskv1.NewTaskServiceClient(m.cli.Conn())
	return client.CancelTask(ctx, in, opts...)
}

func (m *defaultTaskService) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error) {
	client := taskv1.NewTaskServiceClient(m.cli.Conn())
	return client.GetTask(ctx, in, opts...)
}

func (m *defaultTaskService) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	client := taskv1.NewTaskServiceClient(m.cli.Conn())
	return client.ListTasks(ctx, in, opts...)
}

func (m *defaultTaskService) GetTaskHistory(ctx context.Context, in *GetTaskHistoryRequest, opts ...grpc.CallOption) (*GetTaskHistoryResponse, error) {
	client := taskv1.NewTaskServiceClient(m.cli.Conn())
	return client.GetTaskHistory(ctx, in, opts...)
}
