// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: dispatcher.proto

package dispatcherservice

import (
	"context"

	dispatcherv1 "github.com/Lio6x1/meshops/gen/dispatcher/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetDispatchRequest  = dispatcherv1.GetDispatchRequest
	GetDispatchResponse = dispatcherv1.GetDispatchResponse
	GetStatusRequest    = dispatcherv1.GetStatusRequest
	GetStatusResponse   = dispatcherv1.GetStatusResponse
	RetryDLQRequest     = dispatcherv1.RetryDLQRequest
	RetryDLQResponse    = dispatcherv1.RetryDLQResponse

	DispatcherService interface {
		// 查询下发记录（一元）
		GetDispatch(ctx context.Context, in *GetDispatchRequest, opts ...grpc.CallOption) (*GetDispatchResponse, error)
		// 手动重试死信任务（一元）
		RetryDLQ(ctx context.Context, in *RetryDLQRequest, opts ...grpc.CallOption) (*RetryDLQResponse, error)
		// 查询分发器运行状态（一元，供监控/运维）
		GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	}

	defaultDispatcherService struct {
		cli zrpc.Client
	}
)

func NewDispatcherService(cli zrpc.Client) DispatcherService {
	return &defaultDispatcherService{
		cli: cli,
	}
}

// 查询下发记录（一元）
func (m *defaultDispatcherService) GetDispatch(ctx context.Context, in *GetDispatchRequest, opts ...grpc.CallOption) (*GetDispatchResponse, error) {
	client := dispatcherv1.NewDispatcherServiceClient(m.cli.Conn())
	return client.GetDispatch(ctx, in, opts...)
}

// 手动重试死信任务（一元）
func (m *defaultDispatcherService) RetryDLQ(ctx context.Context, in *RetryDLQRequest, opts ...grpc.CallOption) (*RetryDLQResponse, error) {
	client := dispatcherv1.NewDispatcherServiceClient(m.cli.Conn())
	return client.RetryDLQ(ctx, in, opts...)
}

// 查询分发器运行状态（一元，供监控/运维）
func (m *defaultDispatcherService) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	client := dispatcherv1.NewDispatcherServiceClient(m.cli.Conn())
	return client.GetStatus(ctx, in, opts...)
}
