// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: task.proto

package server

import (
	"context"

	"github.com/Lio6x1/meshops/app/task/internal/logic/taskservice"
	"github.com/Lio6x1/meshops/app/task/internal/svc"
	taskv1 "github.com/Lio6x1/meshops/gen/task/v1"
)

type TaskServiceServer struct {
	svcCtx *svc.ServiceContext
	taskv1.UnimplementedTaskServiceServer
}

func NewTaskServiceServer(svcCtx *svc.ServiceContext) *TaskServiceServer {
	return &TaskServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *TaskServiceServer) CreateTask(ctx context.Context, in *taskv1.CreateTaskRequest) (*taskv1.CreateTaskResponse, error) {
	l := taskservicelogic.NewCreateTaskLogic(ctx, s.svcCtx)
	return l.CreateTask(in)
}

func (s *TaskServiceServer) CancelTask(ctx context.Context, in *taskv1.CancelTaskRequest) (*taskv1.CancelTaskResponse, error) {
	l := taskservicelogic.NewCancelTaskLogic(ctx, s.svcCtx)
	return l.CancelTask(in)
}

func (s *TaskServiceServer) GetTask(ctx context.Context, in *taskv1.GetTaskRequest) (*taskv1.GetTaskResponse, error) {
	l := taskservicelogic.NewGetTaskLogic(ctx, s.svcCtx)
	return l.GetTask(in)
}

func (s *TaskServiceServer) ListTasks(ctx context.Context, in *taskv1.ListTasksRequest) (*taskv1.ListTasksResponse, error) {
	l := taskservicelogic.NewListTasksLogic(ctx, s.svcCtx)
	return l.ListTasks(in)
}

func (s *TaskServiceServer) GetTaskHistory(ctx context.Context, in *taskv1.GetTaskHistoryRequest) (*taskv1.GetTaskHistoryResponse, error) {
	l := taskservicelogic.NewGetTaskHistoryLogic(ctx, s.svcCtx)
	return l.GetTaskHistory(in)
}
