// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: ingest.proto

package server

import (
	"github.com/Lio6x1/meshops/app/ingest/internal/logic/ingestservice"
	"github.com/Lio6x1/meshops/app/ingest/internal/svc"
	ingestv1 "github.com/Lio6x1/meshops/gen/ingest/v1"
)

type IngestServiceServer struct {
	svcCtx *svc.ServiceContext
	ingestv1.UnimplementedIngestServiceServer
}

func NewIngestServiceServer(svcCtx *svc.ServiceContext) *IngestServiceServer {
	return &IngestServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *IngestServiceServer) ReportEntityStates(stream ingestv1.IngestService_ReportEntityStatesServer) error {
	l := ingestservicelogic.NewReportEntityStatesLogic(stream.Context(), s.svcCtx)
	return l.ReportEntityStates(stream)
}
