// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: entity.proto

package server

import (
	"context"

	"github.com/Lio6x1/meshops/app/entity/internal/logic/entityservice"
	"github.com/Lio6x1/meshops/app/entity/internal/svc"
	entityv1 "github.com/Lio6x1/meshops/gen/entity/v1"
)

type EntityServiceServer struct {
	svcCtx *svc.ServiceContext
	entityv1.UnimplementedEntityServiceServer
}

func NewEntityServiceServer(svcCtx *svc.ServiceContext) *EntityServiceServer {
	return &EntityServiceServer{
		svcCtx: svcCtx,
	}
}

// 订阅实体更新（服务端流）
func (s *EntityServiceServer) Subscribe(in *entityv1.SubscribeRequest, stream entityv1.EntityService_SubscribeServer) error {
	l := entityservicelogic.NewSubscribeLogic(stream.Context(), s.svcCtx)
	return l.Subscribe(in, stream)
}

// 获取单个快照（一元）
func (s *EntityServiceServer) GetSnapshot(ctx context.Context, in *entityv1.GetSnapshotRequest) (*entityv1.GetSnapshotResponse, error) {
	l := entityservicelogic.NewGetSnapshotLogic(ctx, s.svcCtx)
	return l.GetSnapshot(in)
}

// 批量获取快照（一元）
func (s *EntityServiceServer) BatchGetSnapshots(ctx context.Context, in *entityv1.BatchGetSnapshotsRequest) (*entityv1.BatchGetSnapshotsResponse, error) {
	l := entityservicelogic.NewBatchGetSnapshotsLogic(ctx, s.svcCtx)
	return l.BatchGetSnapshots(in)
}
