Name: course-z05
ListenOn: 127.0.0.1:25251
Mode: dev
Timeout: 5000
Telemetry:
  Name: course-z05
  Endpoint: ""
MeshOps:
  Manifest: simulation.yaml
  TopicPrefix: z05-
  ConsumerGroupPrefix: z05-
  KafkaBrokers: [localhost:29092]
  RedisAddr: 127.0.0.1:26379
