// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: dispatcher.proto

package server

import (
	"context"

	"github.com/Lio6x1/meshops/app/dispatcher/internal/logic/dispatcherservice"
	"github.com/Lio6x1/meshops/app/dispatcher/internal/svc"
	dispatcherv1 "github.com/Lio6x1/meshops/gen/dispatcher/v1"
)

type DispatcherServiceServer struct {
	svcCtx *svc.ServiceContext
	dispatcherv1.UnimplementedDispatcherServiceServer
}

func NewDispatcherServiceServer(svcCtx *svc.ServiceContext) *DispatcherServiceServer {
	return &DispatcherServiceServer{
		svcCtx: svcCtx,
	}
}

// 查询下发记录（一元）
func (s *DispatcherServiceServer) GetDispatch(ctx context.Context, in *dispatcherv1.GetDispatchRequest) (*dispatcherv1.GetDispatchResponse, error) {
	l := dispatcherservicelogic.NewGetDispatchLogic(ctx, s.svcCtx)
	return l.GetDispatch(in)
}

// 手动重试死信任务（一元）
func (s *DispatcherServiceServer) RetryDLQ(ctx context.Context, in *dispatcherv1.RetryDLQRequest) (*dispatcherv1.RetryDLQResponse, error) {
	l := dispatcherservicelogic.NewRetryDLQLogic(ctx, s.svcCtx)
	return l.RetryDLQ(in)
}

// 查询分发器运行状态（一元，供监控/运维）
func (s *DispatcherServiceServer) GetStatus(ctx context.Context, in *dispatcherv1.GetStatusRequest) (*dispatcherv1.GetStatusResponse, error) {
	l := dispatcherservicelogic.NewGetStatusLogic(ctx, s.svcCtx)
	return l.GetStatus(in)
}
