// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: entity.proto

package entityservice

import (
	"context"

	entityv1 "github.com/Lio6x1/meshops/gen/entity/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchGetSnapshotsRequest  = entityv1.BatchGetSnapshotsRequest
	BatchGetSnapshotsResponse = entityv1.BatchGetSnapshotsResponse
	EntityUpdate              = entityv1.EntityUpdate
	GetSnapshotRequest        = entityv1.GetSnapshotRequest
	GetSnapshotResponse       = entityv1.GetSnapshotResponse
	SubscribeRequest          = entityv1.SubscribeRequest

	EntityService interface {
		// 订阅实体更新（服务端流）
		Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (entityv1.EntityService_SubscribeClient, error)
		// 获取单个快照（一元）
		GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*GetSnapshotResponse, error)
		// 批量获取快照（一元）
		BatchGetSnapshots(ctx context.Context, in *BatchGetSnapshotsRequest, opts ...grpc.CallOption) (*BatchGetSnapshotsResponse, error)
	}

	defaultEntityService struct {
		cli zrpc.Client
	}
)

func NewEntityService(cli zrpc.Client) EntityService {
	return &defaultEntityService{
		cli: cli,
	}
}

// 订阅实体更新（服务端流）
func (m *defaultEntityService) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (entityv1.EntityService_SubscribeClient, error) {
	client := entityv1.NewEntityServiceClient(m.cli.Conn())
	return client.Subscribe(ctx, in, opts...)
}

// 获取单个快照（一元）
func (m *defaultEntityService) GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*GetSnapshotResponse, error) {
	client := entityv1.NewEntityServiceClient(m.cli.Conn())
	return client.GetSnapshot(ctx, in, opts...)
}

// 批量获取快照（一元）
func (m *defaultEntityService) BatchGetSnapshots(ctx context.Context, in *BatchGetSnapshotsRequest, opts ...grpc.CallOption) (*BatchGetSnapshotsResponse, error) {
	client := entityv1.NewEntityServiceClient(m.cli.Conn())
	return client.BatchGetSnapshots(ctx, in, opts...)
}
